# Generated by Django 2.2.13 on 2020-07-05 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
                ('overview', models.TextField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('besttime', models.CharField(max_length=150, null=True)),
                ('howtoreach', models.CharField(max_length=250, null=True)),
                ('nativelang', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('mainphoto', models.CharField(max_length=65, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=15)),
                ('bookingtype', models.CharField(choices=[('none', 'None'), ('day', 'Day'), ('seat', 'Seat'), ('ticket', 'Ticket')], default='none', max_length=15)),
                ('booking_price', models.FloatField(null=True)),
                ('amenities', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Amenity')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Locality')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placeid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='')),
                ('place', models.CharField(default='', max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspend', 'Suspend')], default='Active', max_length=7)),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User_gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=25, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=25, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User')),
            ],
        ),
    ]
