# Generated by Django 2.2.13 on 2020-07-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cardholder_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cardnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='cvv',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='expdate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='expyear',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
