# Generated by Django 2.2.13 on 2020-07-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200706_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='booking_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
