# Generated by Django 2.2.13 on 2020-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_orders_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('establishment', 'Establishment')], default='user', max_length=7),
        ),
    ]
