# Generated by Django 2.2.13 on 2020-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200712_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('owner', 'Owner')], default='user', max_length=7),
        ),
    ]
