# Generated by Django 2.2.13 on 2020-07-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200712_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='placeid',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userid',
        ),
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Place'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User'),
        ),
    ]
